### ISSUE TITLE
Migliorie 

### ISSUE THREAD

**Issue by LanmanGroup** [Zexal0807/TEST_argomenti1234#1]
- [x] usare form!
- [x] migliorare input type
- [x] required?
- [x] mancano dettagli sui campi obbligatori
- [x] manca conferma di invio
- [x] rimuovere alert e mostrare result in altro modo

**Comment by Zexal0807** [comment]
Cosa si intente per migliorare input type?

**Comment by LanmanGroup** [comment]
per Safari potresti usare https://www.w3schools.com/tags/att_input_type_tel.asp

**Comment by Zexal0807** [comment]
Ok, l'avevo già visto, ma l'avevo scartato dato che Safari è poco usato rispetto ad altri browser

**Comment by LanmanGroup** [comment]
Usare form significa anche usare l'evento submit e non evento click sul bottone

**Comment by LanmanGroup** [comment]
Alla submit del form non capisco quale campo non è compilato, non ho feedback. 

Se avessi rimosso la funzione isValid e avessi lasciato gli attributi di html5 `required` ed usato in modo corretto il form e l'evento `submit` avresti visto dove sta l'errore di compilazione.

Se introduci una validazione lato javascript (che mi va anche bene) va fatta completa, con feedback.

**Comment by LanmanGroup** [comment]
Nel campo email posso inserire una qualunque stringa, manca validazione

**Comment by LanmanGroup** [comment]
Non c'è "conclusione" dopo la submit, le modal restano aperte e manca di feedback.

**Comment by Zexal0807** [comment]
> Usare form significa anche usare l'evento submit e non evento click sul bottone

Non riesco a capire, se metto il submit al form, dopo viene ricaricata la pagina e quindi l'ajax perde di significato, e non può mostrare il risultato

**Comment by LanmanGroup** [comment]
Puoi fare una submit in ajax... serializzando i dati del form oppure usando plugin ad hoc, ti butto li uno spunto

```js
$(document).on('submit', 'form', function (e) {
    e.preventDefault();
    $form = $(e.target);
.....
```

**Comment by Zexal0807** [comment]
Sistemato submit via ajax
